### ISSUE TITLE
Modify makefile to build rpm successfully through 'make --all' command

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#103]

**Comment by gnehapk** [comment]
@TimothyAsir Please have a look to makefile as we are not able to create rpm successfully through make --all command.

**Comment by TimothyAsir** [comment]
@gnehapk Could you try "make setup" and run "make rpm" ? and let me know whether you are able to build the rpm.

**Comment by TimothyAsir** [comment]
@gnehapk , I have send a pr https://github.com/Tendrl/dashboard/pull/201 which does not required any make setup. It will pickup the required java build packaged at run-time from the tendrl-dashboard-build-packages tar at the build time. You can just run "make rpm" to build the rpm once the PR is merged.
This issue can be closed after the PR is merged.
