### ISSUE TITLE
Primary navigation styling is inconsistent with design intent

### ISSUE THREAD

**Issue by mcarrano** [Tendrl/dashboard#114]
Primary navigation items should not have icons and should be styled according to these UI mockups.  Not hover and selected states for secondary icons within the Admin section.

See https://redhat.invisionapp.com/share/9XA4GEF4V  for high-fidelity UI mockup.

**Comment by mkudlej** [comment]
Thank you for design. I've put there some comments which are unrelated to navigation, sorry about that. Could you please recommend me better design document for comments like that?

**Comment by mcarrano** [comment]
@mkudlej Looks like all of your comments relate to the dashboard.  We do have a separate design document to address dashboard designs here: https://redhat.invisionapp.com/share/589XIRJBW  Please feel free to add your comments there and we will address them.

**Comment by cloudbehl** [comment]
Pull request for this issue has been sent. #158

**Comment by gnehapk** [comment]
Merged in master. Hence closing this issue.
