### ISSUE TITLE
bad return value for nodes

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#117]
No nodes are displayed on UI as list/array is expected as return value, but gets dictionary. 
Error: [filter:notarray] Expected array but received: {"nodes":[{"node_id":"f9d9928a-bc15-40e0-8bcd-fa7f8ecb3eea","status":"UP","tags":"tendrl/node\ngluster/server","fqdn":"ltrilety-usm5-node1.usmqe.lab.eng.brq.redhat.com"," ...

The issue could be seen on:
tendrl-api-1.2-01_31_2017_01_51_02.noarch
tendrl-api-httpd-1.2-01_31_2017_01_51_02.noarch
tendrl-frontend-1.1-1.el7.centos.noarch
tendrl-api-doc-1.2-01_31_2017_01_51_02.noarch

Reproduction scenario:
1. Install tendrl, connect some nodes (install and configure tendrl agents)
2. Check that nodes are connected (see etcd on server)
3. Open GUI
4. Click on Nodes - see firebug console output

**Comment by brainfunked** [comment]
It's a change in the API response that is being documented and should be available later today. Apart from that, would you mind explaining why this is a dashboard issue?

**Comment by ltrilety** [comment]
Because it's frontend problem hence dashboard issue.

**Comment by ltrilety** [comment]
![no_array](https://cloud.githubusercontent.com/assets/22369834/22461697/93561ff4-e7aa-11e6-985a-e0f3e0b93a46.png)

**Comment by ltrilety** [comment]
We have been installing bad package for GUI tendril-frontend instead of tendrl-dashboard. Seems to be working after I replaced those two.
