### ISSUE TITLE
Data points required for Dashboard UI

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#120]
**Ceph**

Dashboard UX - https://redhat.invisionapp.com/share/589XIRJBW#/screens/213318367

What Is needed: 
host quorum value? 
Utilization - by storage profile?(Is this the aggregate of all the cluster)?
Utilization - the trendline should be according the time frame? (Array of timeframe is required)
Alerts and Warnings for Hosts, Monitors, PG's and OSDs (Need Alerts and Warning for all this).
Number of Hosts, Monitors, PGs and OSD count?
Pools, RBDs > Busiest - values?
Pools, RBDs > Highest Latency values?

**Comment by cloudbehl** [comment]
@anmolbabu Please have a look.

**Comment by nthomas-redhat** [comment]
@anmolbabu all the data points mentioned above are taken care. Please update
