### ISSUE TITLE
Integrate UI with latest API response

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#125]

**Comment by gnehapk** [comment]
Changes in API response - 

1) http://10.70.43.173:9292/1.0/6b4b84e0-17b3-4543-af9f-e42000c52b55/Flows API is giving 404

-  Node List 
   1) "tags" - it is changed from "ceph/mon" to "tendrl/node\nceph/mon"
   
- Cluster List 
   1) "sds_name" - it is changed from "gluster" to "glusterfs"

**Comment by cloudbehl** [comment]
@anivargi We are able to find these new changes in the API. Please verify if we can start with UI changes accordingly.

**Comment by anivargi** [comment]
@cloudbehl you are using a old instance, we need to update that.

**Comment by brainfunked** [comment]
Also, tags must always be assumed to be a list. You need to filter out the tags which match the specific storage system you're currently displaying. Hence, the tags are hierarchical.

**Comment by cloudbehl** [comment]
@anivargi so can you provide the link to a new instance or updated instance?
