### ISSUE TITLE
Need UX design for CRUD operation on pool/rbd 

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/dashboard#126]
We need UX design for CRUD operation on pool and rbd .

basically pool can have these CRUD operation as per UX design (https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417118 ) : 
 - Edit pool 
 - Grow PGs for pool 
 - Remove pool 

and pool can have these CRUD operation as per UX design ( https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417119 ) :

- Remove RBDs
- Resize RBDs

**Comment by kamleshverma1** [comment]
@julienlim @mcarrano Please can we have UX design for CRUD operation on pool and rbd as per above statement.

**Comment by julienlim** [comment]
@kamleshverma1 @mcarrano The edit pool, grow pg, and resize rbd is in progress.  We should have that by end of this week.

**Comment by julienlim** [comment]
Resize RBD design just posted to https://redhat.invisionapp.com/share/Z9AE9W6H4.

**Comment by sankarshanmukhopadhyay** [comment]
@kamleshverma1 since the UX designs are now available, I am closing this. Reviews/clarification on the designs provided are expected to be via the invisionapp
