### ISSUE TITLE
Cluster name is not present in Cluster list response

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/dashboard#128]
Cluster name is not present in Cluster list response:

{"clusters":[{"sds_name":"glusterfs","sds_version":"3.9.1","integration_id":"d250df46-e1de-4070-b6b5-32fde35d27a3","cluster_id":"d250df46-e1de-4070-b6b5-32fde35d27a3"}]}

it should contain cluster name in order to populate cluster name on UI.

**Comment by kamleshverma1** [comment]
@anivargi @nthomas-redhat cluster list response should contain cluster name in order to populate cluster name on UI. Please can we have this property on response ?

**Comment by cloudbehl** [comment]
Issue Fixed - The name for Ceph and Gluster is coming in the API now.Issue.
