### ISSUE TITLE
lists update

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#133]
Items (Volumes) created by API never shows on GUI if the page is not refreshed. Clicking on menu doesn't help.

tested on:
tendrl-api-httpd-1.2-02_08_2017_01_51_04.noarch
tendrl-dashboard-1.2-02_08_2017_04_11_02.noarch

**Comment by cloudbehl** [comment]
@kamleshverma1 please have a look.

**Comment by nthomas-redhat** [comment]
@gnehapk @cloudbehl What is the UI refresh interval?

**Comment by gnehapk** [comment]
@nthomas-redhat 10 secs.

**Comment by nthomas-redhat** [comment]
@ltrilety You would be able to see item created through API calls once UI is refreshed. I am closing this issue.
