### ISSUE TITLE
Lists views should not show actions for unsupported pool/file share types

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#134]
@kamleshverma1 @cloudbehl @gnehapk 

As Tendrl needs to tolerate unsupported unsupported Ceph pools (EC) and unsupport Gluster (distributed, replicated, etc.) volume types in the Tendrl UI, we need to be able to list them in the list views.  However, we should not permit Day 2 operations/actions on them (e.g. expansion and modification. 

In the 7 Feb 2017 demo (https://bluejeans.com/s/VC32c/), the File Share list view shows the "kebab" menu for a "Distribute" file share/volume.  As this is an unsupported volume type, we would suggest
not showing the "kebab" at the end of the row.  If however, there is a single action we may support, e.g. "Delete" then we would show the "Delete" action.  Note: The "Delete" action question is pending on a question I raised in https://tendrl.atlassian.net/browse/TEN-149.

Specifically, what if I delete a Gluster volume (that is not supported) that was previously imported in Tendrl. Will the monitoring pick that up? How will Tendrl treat this? Is this volume now orphaned (and so we now need a "Unmanage" it in the UI), or will it automatically be removed from Tendrl (etcd) and user does not need to do anything about it in the UI/API?

@mkudlej @mcarrano Just a FYI.  It's not documented in the list view design but noted here.

**Comment by cloudbehl** [comment]
Issue is fixed in #148 pull request. 
@mkudlej @mcarrano latest master has these changes.
