### ISSUE TITLE
End points are giving 404 NOT found error.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#153]
I tried using a curl command for resizeRBD and updatePool and the endpoints are giving 404 error.

curl -XPUT -d '{"Rbd.pool_id":"4","Rbd.name":"mmrbd1","Rbd.size":1048}' http://10.70.43.162:9292/1.0/e73b770e-5d3c-475e-87e2-c83e7deb2f15/CephResizeRbd

curl -XPUT -d '{"Pool.pool_id":"3","Pool.poolname":"test-test-1","Pool.pg_num":64,"Pool.min_size":1}' http://10.70.43.162:9292/1.0/e73b770e-5d3c-475e-87e2-c83e7deb2f15/CephUpdatePool

Both of the above commands are giving 404 error, so the UI team is not able to test the UI for the same.

**Comment by cloudbehl** [comment]
@nthomas-redhat @anivargi @shtripat @r0h4n @brainfunked We need to fix this issue.

**Comment by sankarshanmukhopadhyay** [comment]
@cloudbehl this is expected to work. One would need to confirm that the instance you are hitting up is configured correctly.

**Comment by gnehapk** [comment]
Fixed.
