### ISSUE TITLE
Vertical Navigation Menu should not have icons

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#155]
Please note that the vertical navigational menu should not have icons in it.  They were removed a long time ago and is reflected in all the designs linked from https://github.com/Tendrl/ui/blob/master/UI%20Designs.adoc.

Decision to remove icons was to reduce confusion of having same icons for all the storage entities.

@gnehapk @kamleshverma1 @cloudbehl
@japplewhite @mcarrano

**Comment by mcarrano** [comment]
This test page shows how the menu should behave from a PatternFly perspective without the icons. https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-with-tertiary-no-icons.html

 Note that clicking the hamburger icon is intended to simply show or hide the primary navigation.

**Comment by cloudbehl** [comment]
@mcarrano @julienlim Fixed and closing the Issue.
