### ISSUE TITLE
Hyperlink needed from "Tendrl" logotype graphic (in banner / masthead)

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#156]
Request to add a (simple static) hyperlink from the "Tendrl" logotype graphic (in banner / masthead area) to the Dashboard page.   The only restriction is that we should not be introducing any visual hover state or other affordance to this graphic to avoid conflicts with branding best practices.

Reason: there is an expectation by users of web-based applications to be able to click on the "Tendrl" logotype graphic to quickly get you back to the default or home page.

@gnehapk @kamleshverma1 @cloudbehl 
@japplewhite @mcarrano

**Comment by cloudbehl** [comment]
#149 similerI Issue

**Comment by cloudbehl** [comment]
@julienlim Will fix it ASAP.

**Comment by cloudbehl** [comment]
@julienlim Fixed and closing this Issue
