### ISSUE TITLE
There is no total value in pool in response data

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/dashboard#171]
there is no total value in pool in the response data .
we need it for displaying progress bar while creating RBD under pool

Here - https://redhat.invisionapp.com/share/EHAC6S0N4#/screens/217735638 . we can see , there is one progress bar that need total and used value for pool. we have used value for pool , but total value is missing .

**Comment by kamleshverma1** [comment]
@nthomas-redhat @shtripat @anivargi Can i get "total value" for pool as per above statement.

**Comment by nthomas-redhat** [comment]
Closing this issue as this is already fixed
