### ISSUE TITLE
UI: Kebab behavior

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#172]
@cloudbehl @gnehapk @kamleshverma1 
@mcarrano 

Once the icons are removed from the vertical navigation menu, we need to ensure the correct behavior for the kebab (aka hamburger) icon, in the top left corner.

Since there are no icons, the menu would just be hidden (i.e. accessible via the kebab only).  This is primarily useful if the user is running on a small monitor or tablet and wants to get more horizontal space.

See https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-with-tertiary-no-icons.html for the kebab icon behavior.

**Comment by gnehapk** [comment]
Fixed. Closing it.
