### ISSUE TITLE
Edit-pool Implementation problem!

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#175]
As per the back-end we need to send the separate call for each property. Like a name of the pool can't be updated along with any other parameter. So the user will need to follow the same edit-pool workflow for updating each parameter.

conditions:
1. pool.id and pool.name
2.  pool.id and pool.size
3. pool.id and pool.pg_num
etc.

I don't think this will not provide a good user experience. So we need to figure out a way to handle this approach. 

Examples:
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.poolname": "zest_pool"}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.size": 2}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.pg_num": 100}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.pg_num": 256}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id": 31, "Pool.min_size": 2}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id": 31, "Pool.quota_enabled": true,
"Pool.quota_max_objects": 10, "Pool.quota_max_bytes": 90}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool

**Comment by cloudbehl** [comment]
@gnehapk @kamleshverma1 @brainfunked @r0h4n @sankarshanmukhopadhyay @nthomas-redhat @shtripat

**Comment by sankarshanmukhopadhyay** [comment]
> I don't think this will not provide a good user experience. So we need to figure out a way to handle this approach.

I understand that you see this as making the UX complicated. Could you add more detail as to why you think so? What is the specific set of issues? What is the suggested alternative that you'd like to have?

**Comment by cloudbehl** [comment]
@sankarshanmukhopadhyay 

Problem: We have given a user an edit page on which he can't edit all the fields together. So there are some conditions in the backend like name should not be updated with size and pg_num(the conditions I mentioned in the Issue).

Set of Conditions shared by @shtripat:
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.poolname": "zest_pool"}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.size": 2}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.pg_num": 100}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id":31, "Pool.pg_num": 256}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id": 31, "Pool.min_size": 2}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool
curl -XPOST -d '{"Pool.pool_id": 31, "Pool.quota_enabled": true,
"Pool.quota_max_objects": 10, "Pool.quota_max_bytes": 90}'
http://10.70.42.39:9292/1.0/d5f2afab-f188-45e8-9af6-8c587dca097f/CephUpdatePool

Alternative approach:
1) Like we know that PG_num should be updated with other properties. Go we have given a separate location for Grow PG's in a kebab[1]. So likewise If a name can't be updated we can add it to the menu by "Edit Name" option in a kebab.
2) We can let a user update every value in edit-pool, but in the backend we should create different requests for the things that can't be updated parallelly. I think those requests needs to be a synchronous call so that each request should not interfere with each other.

[1]. https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417118

**Comment by r0h4n** [comment]
The UI can fire multiple dependent sequential API jobs for editing 1) Pool name 2) other attributes once #1 is finished.

This is a Ceph land limitation, I cannot think of a non complicated way of doing this in the backend

**Comment by sankarshanmukhopadhyay** [comment]
Have we checked whether it is feasible for the UI to adopt the approach mentioned at https://github.com/Tendrl/dashboard/issues/175#issuecomment-291428062 ?

**Comment by cloudbehl** [comment]
@sankarshanmukhopadhyay  @r0h4n ideally in the scenario you have suggested the UI will fire two post request. And the task page will have two task for the single click that end user has fired and will lead to confusion for the end user. 
So, I think it's better to separate the edit Name from edit pool and one more statement will be added to the kebab menu with the name "Edit Name".

**Comment by shtripat** [comment]
@cloudbehl go ahead and get a sign off from Ju on this movement of option to kebab menu.
I dont feel any change required in backend as such in that case. Still let me know if you face any issues.

**Comment by julienlim** [comment]
@cloudbehl @sankarshanmukhopadhyay @r0h4n @mcarrano @gnehapk @kamleshverma1 @brainfunked @r0h4n @nthomas-redhat @shtripat

In reviewing the comments on the ask to separate the pool rename from the rest of the Edit Pool, while not ideal, we can live with separating it for now due to the current Ceph limitations.  Since we are going to perform object rename separately from the rest of the configuration changes on the object, we will need this behavior to be consistent with the rest of the UI.  Specifically, this now means we will have to volume / file share rename separately as well.  What this means is this from a UI/UX perspective:
* List views for pool and file share (volume) will now include an action for renaming pool and file share.
* Removing pool name editing from Edit Pool workflow
* Removing file share name editing from Edit File Share workflow
* Add the rename action to the object details view for Pool and File Share

Note that even though we're going down this path, the need to fire multiple API calls for other Day 2 operations is very likely, e.g. replace disk, replace host, etc.  While we don't have to deal with too many Day 2 operations just yet, at some point the ability to group multiple API calls generated (sub)tasks into a single task will be needed in a not too distant future.

**Comment by julienlim** [comment]
@cloudbehl @sankarshanmukhopadhyay @r0h4n @mcarrano @gnehapk @kamleshverma1 @brainfunked @r0h4n @nthomas-redhat @shtripat @japplewhite @mkudlej @mbukatov 

We have updated the wireframes to now include the rename pool action.

Updates for Ceph include the following:
- Added design for [Rename Pool](https://redhat.invisionapp.com/share/THAEA6CEA#/screens/227875971)
- [List Pools design](https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417118) now includes the "Rename" action
- [Edit Pool design](https://redhat.invisionapp.com/share/THAEA6CEA#/screens/218370286) no longer allows the user to edit pool name in its workflow

**Comment by mbukatov** [comment]
@Tendrl/qe : fyi
