### ISSUE TITLE
`Server not found (404) !` message when no cluster is imported

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#176]
There is displayed `Server not found (404) !` message and there is no `import cluster` option selection in UI when I load homepage without any imported cluster. Attached screenshot.

Tested with:
tendrl-api-1.2.1-03_02_2017_01_51_02.noarch
tendrl-dashboard-1.2.1-03_02_2017_12_19_25.noarch
tendrl-performance-monitoring-1.2.1-03_02_2017_03_02_02.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-node-agent-1.2.1-03_02_2017_00_01_02.noarch

**Comment by fbalak** [comment]
![screenshot_20170302_125446](https://cloud.githubusercontent.com/assets/22369801/23506818/65829a82-ff4a-11e6-9a65-4707d8b57296.png)

**Comment by fbalak** [comment]
Maybe related to https://github.com/Tendrl/api/issues/89.

**Comment by julienlim** [comment]
@gnehapk @cloudbehl @kamleshverma1 It appears that there's something broken in the UI when there are no clusters.

**Comment by kamleshverma1** [comment]
We are calling GetClusterList api in landing page only . and in case of 404 error from api itself . it will show "Server not found" in UI. so ideally this issue fixed from API level so that it should not come as 404 in api response if tendrl-api server is running . and if there is no cluster in the list than it should have some empty json response .not a 404 error.

**Comment by sankarshanmukhopadhyay** [comment]
@anivargi - could you take a look and appropriate accordingly?

**Comment by sankarshanmukhopadhyay** [comment]
Is this an issue that needs to be fixed or, is this blocking tests from progressing? At present it is listed under https://github.com/Tendrl/usmqe-tests/wiki#blockers @brainfunked - would it be possible for you to take a look at this?

**Comment by anivargi** [comment]
@sankarshanmukhopadhyay the commit https://github.com/Tendrl/api/issues/89 of API should address it.

**Comment by fbalak** [comment]
It looks ok. Tested with:
tendrl-api-1.2.1-03_08_2017_01_51_04.noarch
tendrl-dashboard-1.2.1-03_08_2017_04_11_03.noarch
