### ISSUE TITLE
Home page still loading

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#178]
Home page seems to be still loading as there is a spinner which never disappears.

![home_page_spinner](https://cloud.githubusercontent.com/assets/22369834/23604390/07105a86-0259-11e7-80aa-e7dd9f488598.png)

Used packages:
tendrl-api-doc-1.2.1-03_06_2017_01_51_02.noarch
tendrl-api-1.2.1-03_06_2017_01_51_02.noarch
tendrl-api-httpd-1.2.1-03_06_2017_01_51_02.noarch
tendrl-dashboard-1.2.1-03_06_2017_11_10_12.noarch

**Comment by cloudbehl** [comment]
@kamleshverma1 please have a look at this.

**Comment by kamleshverma1** [comment]
@cloudbehl @ltrilety @gnehapk  sent patch for fixed this issue : 
https://github.com/Tendrl/dashboard/pull/180

**Comment by cloudbehl** [comment]
@ltrilety please verify and close this Issue.

**Comment by ltrilety** [comment]
@cloudbehl Once UI will work, I'll check that. As of now authentication is not counted with in current tendrl-dashboard package.

**Comment by ltrilety** [comment]
Seems OK.
Checked on:
tendrl-api-doc-1.2.2-04_06_2017_01_51_04.noarch
python-etcd-0.4.3-1.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_06_2017_10_49_10.noarch
tendrl-performance-monitoring-1.2.2-04_06_2017_03_02_03.noarch
tendrl-api-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-httpd-1.2.2-04_06_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
etcd-3.1.0-2.el7.x86_64
rubygem-etcd-0.3.0-1.el7.centos.noarch
