### ISSUE TITLE
Branching model needs improvement

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/dashboard#195]
Please follow below branching model for better categorization of code which will allow devs to push code in parallel without regressions:

http://nvie.com/posts/a-successful-git-branching-model/

Check how its done on the node-agent or the commons/ceph/gluster-integration repositories

**Comment by cloudbehl** [comment]
@r0h4n I have gone through the document and have create the develop branch. Dashboard will be following the branching model from now.

You can check the desired changes[1].
[1]. https://github.com/Tendrl/dashboard/branches
