### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by karnan4ever** [Tendrl/dashboard#20]
- Unit testing libraries should be used

**Comment by TimothyAsir** [comment]
Could you please elaborate a bit more and share your views about how do you want us or what are the best unit testing libraries shall we use?

**Comment by karnan4ever** [comment]
@TimothyAsir we are already using unit test libraries. @gnehapk @kamleshverma1 @debloper can anyone close after adding details on unit test tools/libraries.

**Comment by gnehapk** [comment]
Integrated testing libraries in the dashboard repo for unit testing. Libraries are -
- mocha
- chai
- sinon
- karma test runner
