### ISSUE TITLE
Authorized API calls

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#203]
All API calls should have `Authorization` header set to proper `access_token` after an user is logged into Tendrl with username and password.

Tested with:
tendrl-dashboard-1.2.1-03_22_2017_04_11_04.noarch
tendrl-api-1.2.1-03_22_2017_17_03_14.noarch

**Comment by sankarshanmukhopadhyay** [comment]
Is this a test blocker or, a recommendation for when implementation is being made available?

**Comment by mkudlej** [comment]
@sankarshanmukhopadhyay It means that authentication and authorization should be implemented in UI. Till then we cannot test UI.

**Comment by mkudlej** [comment]
This issue is also related to https://github.com/Tendrl/dashboard/issues/202

**Comment by nthomas-redhat** [comment]
fix is in progress. @gnehapk please updates once it is done

**Comment by cloudbehl** [comment]
#205 @fbalak @mkudlej @nthomas-redhat  The fix is now present in UI.

**Comment by ltrilety** [comment]
There's login page present on UI, however import of cluster cannot be done. After login it says `Server not found!`.

Tested with:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch

**Comment by sankarshanmukhopadhyay** [comment]
Ah! @ltrilety this is an issue which @brainfunked and @nthomas-redhat identified and worked on y'day. I'll leave it to them to provide the answer. @anivargi I think the *-api RPMs would need a fix/bump of sorts for the NVR.

**Comment by ltrilety** [comment]
@fbalak authentication seems to be working, you could close this issue.

**Comment by fbalak** [comment]
Login works. --> closing
