### ISSUE TITLE
Create Ceph Cluster Implementation

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#206]

**Comment by gnehapk** [comment]
Needs clarity on -

- Fields/parameters/actions to be implemented in UI which are supported by backend

- Request data to be send in the create cluster POST call

@nthomas-redhat @brainfunked @r0h4n @shtripat Please reply to above questions.

**Comment by sankarshanmukhopadhyay** [comment]
There is work on the spec at https://github.com/Tendrl/specifications/pull/146 and the UX spec is at https://redhat.invisionapp.com/share/2K8M4PQYZ#/screens At this point we are only doing colocated journals.
