### ISSUE TITLE
Not able to test few flows on UI related to gluster cluster 

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#210]
Not able to test following views as gluster cluster is not available  -

1) File share list
2) RBD list 
3) Gluster object list views 
    - Host List
    - File Share List
    - Rbd List 

@brainfunked @nthomas-redhat @r0h4n @anivargi @sankarshanmukhopadhyay Please provide a gluster cluster.

**Comment by gnehapk** [comment]
@brainfunked @nthomas-redhat @r0h4n @anivargi @sankarshanmukhopadhyay  No cluster is present for importing. Hence we are not able to test import cluster functionality too.

**Comment by nthomas-redhat** [comment]
This is not valid anymore. Closing the issue
