### ISSUE TITLE
Build rpms in copr for branch "release/$nvr"

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/dashboard#215]
Tendrl rpms are built for master and develop branch on copr.

We need Tendrl rpms to be built for release branches too eg: "release/1.2.2"

The rpm nvr should not contain datetime, it should only contain the nvr as given in spec file at branch "release/$version"

**Comment by nthomas-redhat** [comment]
@r0h4n Right now it is built in copr under tendrl/release. hope that is what you are looking for.

@TimothyAsir , we don't need to enable the nightly builds on release branches. Please disable that.

**Comment by r0h4n** [comment]
Yes this can closed.

We do need frequent builds on release branch too. That's because we are backporting fixes and they need to be built
