### ISSUE TITLE
Changes required for Edit pool.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#218]
As per the discussions on the Issue(https://github.com/Tendrl/dashboard/issues/175). The Pool name and Other parameters cannot be edited at the same time.

@julienlim  please go through the issue #175. We need to add one more value to kebab menu of pool list view and create a separate UI and UX for Edit Pool Name.

**Comment by julienlim** [comment]
@cloudbehl I will comment directly on issue #175.

**Comment by nthomas-redhat** [comment]
Duplicate of https://github.com/Tendrl/dashboard/issues/175
