### ISSUE TITLE
A login page always call logout API request

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#221]
When login page is shown a `logout` API call request can be found in firebug console. It doesn't make sense as login page is accessible only when no user is logged in.

![image](https://cloud.githubusercontent.com/assets/22369834/24696243/16b7a1cc-19e9-11e7-9e0b-2757bfa22c4f.png)

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by sankarshanmukhopadhyay** [comment]
@anivargi if this is not fixed in the current package set, could you make it as one of the issues we fix in the next package build set?

**Comment by cloudbehl** [comment]
@ltrilety The bug is fixed from our side. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by ltrilety** [comment]
No unnecessary logout called.
Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
