### ISSUE TITLE
First login with no cluster imported

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#222]
First cluster cannot be imported using UI as it says `Server not found!`

![image](https://cloud.githubusercontent.com/assets/22369834/24696501/fc07fc68-19e9-11e7-8842-b8888bc5d559.png)

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by sankarshanmukhopadhyay** [comment]
@brainfunked can we get this sorted? We hit this issue y'day and it was resolved. Aren't the packages on master yet?

**Comment by mkudlej** [comment]
I would like to mention  that until there is fix for this issue we cannot verify cluster creation from UI. There is potential workaround that we can import Gluster cluster and then try to create Ceph cluster. I'll try it.

**Comment by mkudlej** [comment]
Ok, this becomes blocker. I haven't found workaround for this.

**Comment by anivargi** [comment]
@mkudlej can you try with the new build 1.2.2-04_05_2017_19_14_15

**Comment by ltrilety** [comment]
@anivargi there's no such build for `tendrl-dashboard` the latest available is 1.2.1-04_06_2017_10_49_10. `tendrl-api` has 1.2.2-04_06_2017_01_51_04.

Anyway I checked the behaviour with another packages and it seems to be working.

Checked with:
tendrl-api-doc-1.2.2-04_06_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.2-04_06_2017_03_02_03.noarch
tendrl-api-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-httpd-1.2.2-04_06_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
