### ISSUE TITLE
Too long default Gluster cluster name

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#223]
What is used as cluster name for gluster trusted pool is too long and it brings a really awful results on UI pages, especially on Hosts page.

![image](https://cloud.githubusercontent.com/assets/22369834/24698455/0210deb6-19f1-11e7-8881-3ba620d6d196.png)

BTW: My resolution was 1280x800, but even with 1680x1050 it was not fine

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by sankarshanmukhopadhyay** [comment]
@gnehapk - do we need to go back to the UX designs for arriving at a good way to handle this?

**Comment by cloudbehl** [comment]
@ltrilety The bug is fixed from our side. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by ltrilety** [comment]
Not the whole cluster name is displayed, it is displayed when mouse cursor hover over the name.

Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
