### ISSUE TITLE
fields overreaching

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#226]
Some fields overreaches to others, whats interesting when down-scaled they stop to do that at some point.

![image](https://cloud.githubusercontent.com/assets/22369834/24698880/7d3b06b0-19f2-11e7-8aaa-ab268fb33f44.png)

![image](https://cloud.githubusercontent.com/assets/22369834/24698986/d8818b16-19f2-11e7-99fa-77d5af2405e0.png)

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by sankarshanmukhopadhyay** [comment]
@gnehapk @cloudbehl - do we need to get back to the UX team in order to get the best approach to resolving this?

**Comment by cloudbehl** [comment]
@sankarshanmukhopadhyay Yes ideally we need their help. As the gluster cluster name Is coming to big. So we need to consult them.
Also, how should it look when we zoom in or zoom out by some percentage.

**Comment by cloudbehl** [comment]
@ltrilety Integration tests are going on will fix this up.

**Comment by cloudbehl** [comment]
@ltrilety  The bug is fixed from our side. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by ltrilety** [comment]
Some fields are still overreaching - hostnames
![image](https://cloud.githubusercontent.com/assets/22369834/24864245/de488a80-1e03-11e7-9a93-002f456fdeea.png)

Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch

**Comment by ltrilety** [comment]
Seems fine.

checked with:
tendrl-dashboard-1.2.3-04_21_2017_04_11_05.noarch
