### ISSUE TITLE
cpu utilization charts on host list of cluster doesn't match reported values

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#227]
Values plotted in donut utilization charts (cpu utilization) on Host
list page doesn't match the actual value (which is shown in a numeric form as
well inside the chart itself).

While the charts report actual utilization value (99 %), the value plotted
(graphical representation) in the donut charts itself doesn't match it, see
attached screenshot, where it looks like the value represented in donut
chart is about 50% instead of expected 99%.

Tested with:
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-performance-monitoring-1.2.2-04_05_2017_13_08_12.noarch
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

![dashboard_charts](https://cloud.githubusercontent.com/assets/22369801/24701576/3dce01c2-19fb-11e7-9b50-ea8c278ad337.png)

It seems that is a similar bug as in Skyring https://bugzilla.redhat.com/show_bug.cgi?id=1358270

**Comment by cloudbehl** [comment]
@fbalak yes a valid Issue, will fix this soon.

**Comment by sankarshanmukhopadhyay** [comment]
There's a bunch of fixes for this which was merged in today. Let us revisit when the RPMs are available off master.

**Comment by cloudbehl** [comment]
@fbalak The bug is fixed from our side. Please verify on the new build[1] available.
@sankarshanmukhopadhyay The RPM is now available off master.
[1]. tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by gnehapk** [comment]
@fbalak Can you please verify and close it, if fixed.

**Comment by fbalak** [comment]
It looks ok.

Tested with:
tendrl-dashboard-1.2.1-04_13_2017_04_11_05.noarch
tendrl-performance-monitoring-1.2.2-04_13_2017_03_02_03.noarch
tendrl-node-agent-1.2.2-04_13_2017_03_06_16.noarch
tendrl-api-1.2.2-04_13_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_13_2017_04_42_04.noarch
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
