### ISSUE TITLE
user cannot logout

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/dashboard#228]
I've tried to logout and it doesn't redirect to login page, see screenshot. 
![bug_tendrl_logout](https://cloud.githubusercontent.com/assets/5920442/24703175/6b098736-1a02-11e7-97c5-2a1b3ba9fdf9.png)

It seems to me that this is related to 
https://github.com/Tendrl/api/issues/118

Anyway calling logout should redirect to login page in case of 
```
404 {"errors":{"message":"Not found."}}
```

**Comment by mkudlej** [comment]
```
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-performance-monitoring-1.2.2-04_05_2017_13_08_12.noarch
```

```
Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
```

**Comment by anivargi** [comment]
@mkudlej it is fixed on master now.

**Comment by fbalak** [comment]
@anivargi which package version?

**Comment by nthomas-redhat** [comment]
@fbalak , This is working on the latest builds. Can you verify and close the issue?

**Comment by fbalak** [comment]
@mkudlej It works as expected. You can close it.
Tested with:
tendrl-commons-1.2.3-04_25_2017_17_15_13.noarch
tendrl-dashboard-1.2.3-04_26_2017_04_11_04.noarch
tendrl-performance-monitoring-1.2.3-04_26_2017_03_02_04.noarch
tendrl-api-1.2.3-04_26_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-04_26_2017_00_01_05.noarch

**Comment by nthomas-redhat** [comment]
Closing the issue per @fbalak comments
