### ISSUE TITLE
GetNodeList and GetClusterList calls on Cluster page

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#229]
Cluster page repeatedly and too often calls GetNodeList and GetClusterList API calls. A new ones are called before the previous ones ends. I don't know exact numbers, but about 40 calls per minute are run.

![image](https://cloud.githubusercontent.com/assets/22369834/24703191/7742fd5c-1a02-11e7-9f60-c3d56303c768.png)

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by ltrilety** [comment]
Another call should not be run if the previous one is not finished regardless how often it is planned to call them.

**Comment by gnehapk** [comment]
@ltrilety Fixed. Available in the new build - tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by ltrilety** [comment]
Fixed

Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch

**Comment by gnehapk** [comment]
@ltrilety If this is verfied, please close the ticket.

**Comment by ltrilety** [comment]
@gnehapk it is already closed
