### ISSUE TITLE
First hit of Hosts page

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#230]
When Hosts page is first opened a `GetNodeList` is called twice at the same time. One `GetNodeList` should be enough for getting all required data. The same can be reproduced with reload of the page.

![image](https://cloud.githubusercontent.com/assets/22369834/24705419/1f45deb2-1a0c-11e7-8638-6d55b2a0c4e1.png)

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by gnehapk** [comment]
@ltrilety First GetNodeList call is a preflight request. It checks for supported methods from the server with an HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method. Hence, in the second GetNodeList call only, actual response is received.

**Comment by ltrilety** [comment]
@gnehapk how is it then both lasts the same time (more than 30 seconds) and both has the same response. Not sure what preflight request should look like, but from what you said it seems to me it should be something easy and fast. Moreover if I go to other page and returns back there's just one call of `GetNodeList`.

**Comment by gnehapk** [comment]
@ltrilety Will check into it.

**Comment by gnehapk** [comment]
@ltrilety Fixed. Available in the new build - tendrl-dashboard-1.2.1-04_09_2017_18_25_13.noarch

**Comment by ltrilety** [comment]
Fixed

Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
