### ISSUE TITLE
If one creates a Pool with a name including spaces it is not listed on the UI

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#231]
A pool with a name as "Yet Another Pool" is not listed on the UI. This is not an problem if the name is of the form "YetAnotherPool"

**Comment by gnehapk** [comment]
@brainfunked @nthomas-redhat @r0h4n @anivargi Can you please check in backend/API as in the UI, we are getting a job id for both scenarios. Is there any limitation on pool name while creating a pool?

**Comment by sankarshanmukhopadhyay** [comment]
It should not be. My recollection of the documentation is that the name of the Pool has to be an unique string. Aside from that, there isn't anything I recall.
