### ISSUE TITLE
Clusters page calls GetNodeList

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#232]
`Clusters` page calls `GetNodeList` API call, moreover it is called repeatedly. Calling `GetClusterList` should be enough. `GetNodeList` should be called only if some details about cluster are required or when is clicked on `Create` or `Import` button. BTW in such cases `GetNodeList` is called again already.

**Comment by sankarshanmukhopadhyay** [comment]
Probably would need looking into along with https://github.com/Tendrl/dashboard/issues/229

**Comment by gnehapk** [comment]
@ltrilety Fixed. Please verify it with the new build  "tendrl-dashboard: 1.2.1-04_09_2017_18_25_13".

**Comment by ltrilety** [comment]
Fixed

Checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
