### ISSUE TITLE
No menu displayed after importing a cluster

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#233]
If a first cluster is imported using UI it states on the `Tasks` page without opening a left menu. After next log-in or after reload of the base URL the base left menu is displayed.

![no_menu](https://cloud.githubusercontent.com/assets/22369834/24753096/0733848a-1ad1-11e7-8fb0-f647389ec583.png)

Used packages:
tendrl-api-doc-1.2.2-04_06_2017_01_51_04.noarch
python-etcd-0.4.3-1.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_06_2017_10_49_10.noarch
tendrl-performance-monitoring-1.2.2-04_06_2017_03_02_03.noarch
tendrl-api-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-httpd-1.2.2-04_06_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
etcd-3.1.0-2.el7.x86_64
rubygem-etcd-0.3.0-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety Fixed. Please verify it with the new build  "tendrl-dashboard: 1.2.1-04_09_2017_18_25_13".

**Comment by ltrilety** [comment]
Menu is displayed correctly, there's a minor issue with the task though. 
By default only task status is displayed no events messages.

![image](https://cloud.githubusercontent.com/assets/22369834/24863243/49d30036-1e00-11e7-92bf-264b468072cb.png)

How it should look like

![image](https://cloud.githubusercontent.com/assets/22369834/24863280/7951d3d2-1e00-11e7-894c-b3de5e3fb5e7.png)

checked with:
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch

**Comment by gnehapk** [comment]
@ltrilety I think the messages endpoint is getting failed(400/404 status). Hence, no event list is getting displayed for the particular task. So can you please confirm weather API response for "messages" is coming or not.

**Comment by ltrilety** [comment]
@gnehapk you're right there was 404 for `messages` call in console.

**Comment by cloudbehl** [comment]
@ltrilety So I think this bug is from API side. So you can file a relative bug in API repository.

**Comment by ltrilety** [comment]
@cloudbehl Ok, so I am closing this one
