### ISSUE TITLE
First load takes 25 seconds

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/dashboard#234]
the initial login to the landing cluster page takes approximately 25 seconds. Needs optimizing.

**Comment by sankarshanmukhopadhyay** [comment]
@r0h4n possibly needs a look at API routines via commons.

**Comment by r0h4n** [comment]
Hey @japplewhite , how does the first load look now?

@cloudbehl could you run the mozilla/chrome built in profiling tests on Tendrl UI and update the report here?

**Comment by japplewhite** [comment]
@r0h4n I'm unable to get into the sandbox..

**Comment by gnehapk** [comment]
@r0h4n Yes We can do it. Created the issue for the same - #336.
