### ISSUE TITLE
PG Count should only accept power of 2 numbers

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#238]
@brainfunked @nthomas-redhat @cloudbehl @gnehapk @japplewhite 

For all Pool-related active management workflows (create pool, grow PG), user is able to set a non-base power of 2 number for PG Count.  Why are we allowing non power of 2 numbers to be specified for the PG value?  E.g. I can change PG num from 128 to 129.  This is not valid and UI ought to prevent against this.

**Comment by cloudbehl** [comment]
@julienlim @Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
@julienlim Actually ceph backend allows any numbers to set as pg_num. So from where this 'power of 2 number  for PG Count' coming from? is it a best practice?

**Comment by julienlim** [comment]
@nthomas-redhat The power of 2 number for PG Count is from PG Calc (see http://ceph.com/pgcalc/).  It is a best practice, but it's also published in our documentation.  If you look at the link you'll see the following:

...
The output value is then rounded to the nearest power of 2.
Tip: The nearest power of 2 provides a marginal improvement in efficiency of the CRUSH algorithm.
If the nearest power of 2 is more than 25% below the original value, the next higher power of 2 is used.

**Comment by nthomas-redhat** [comment]
Ok. This is implemnted in the UI. Hence closing this issue
