### ISSUE TITLE
Create RBD workflow, extra buttons visible

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#239]
@cloudbehl @gnehapk 

During RBD creation, if you create a new pool vs. use an existing pool, you see 2 sets of buttons (t the bottom of the wizard.  User does not expect to see duplicate buttons.

**Comment by cloudbehl** [comment]
@julienlim @Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
This is fixed. closing the issue
