### ISSUE TITLE
Create Pool workflow: typo in PG Count entry “… later ,you …”

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#240]

**Comment by sankarshanmukhopadhyay** [comment]
Can we include this fix in the upcoming code push?

**Comment by a2batic** [comment]
I would like to work on this issue

**Comment by cloudbehl** [comment]
@julienlim @Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
