### ISSUE TITLE
Create Pool workflow: if user selects EC and 2+1, why do we still see Replicas?

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#241]

**Comment by nthomas-redhat** [comment]
duplicate of https://github.com/Tendrl/dashboard/issues/237

**Comment by cloudbehl** [comment]
@julienlim @Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
