### ISSUE TITLE
Pools List view: EC pool should not have Replicas and should show k+m values instead

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#243]

**Comment by cloudbehl** [comment]
duplicate of #237

**Comment by cloudbehl** [comment]
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
