### ISSUE TITLE
RBD resizing let’s user specify unrealistic values (beyond what you actually have) without any warning message

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#244]

**Comment by cloudbehl** [comment]
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by julienlim** [comment]
@gnehapk I looked at the bug fix on this, but the accepted values still allow for certain values that not be allowed.  

Specifically, the Rules of Thumbs for calculating PG’s from Ceph documentation:
If <5 OSDs, PG = 128
If 5-10 OSDs, then PG = 512
If 10-50 OSDs, then PG = 4096
If > 50 OSD’s use PGCalc

The default PG is 8 when you setup a Ceph cluster with all defaults.

Allowing PG values of 1, 2, 4 does not make sense -- please remove.

I also noticed that when I try to type over the PG value, the UI starts to increase the PG values to other values, which is unusual behavior.  It would be ideal that the value does not change and that user can only use the spinner to adjust the value.

**Comment by gnehapk** [comment]
@julienlim Will take care of it.

@julienlim @sankarshanmukhopadhyay @nthomas-redhat @brainfunked Can you please provide us the list of default and unrealistic(validation needs to be done) values for the fields present in the UI views as I can't see it on the UX mockups.

**Comment by julienlim** [comment]
@gnehapk Please also note that the user can never lower the PG value from what it's currently set at.  It seems to allow me to lower it 0, which should not be valid.  I just tried it and it let me set PG count to 0!

**Comment by julienlim** [comment]
@gnehapk The power of 2 numbers can be seen at https://en.wikipedia.org/wiki/Power_of_two.  Please do not let user lower the PG value -- this is not possible on Ceph and also not allowed, so UI should not allow it too.
