### ISSUE TITLE
Admin > Tasks: I can see a Task List, but there’s no timestamp (just date) and by who on the Submitted column.

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#246]

**Comment by cloudbehl** [comment]
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
