### ISSUE TITLE
Hosts List View: we should not show NaN% or “- of -“ used for Memory.  Is it 0% or No Data?  We have existing PF treatment for how to deal with No Data,

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#247]

**Comment by nthomas-redhat** [comment]
@anmolbabu , what is the API response in case if `No Data` available or 0%

**Comment by gnehapk** [comment]
Fixed in the build "tendrl-dashboard: 1.2.1-04_09_2017_18_25_13".

**Comment by cloudbehl** [comment]
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by julienlim** [comment]
Just adding a screenshot from the previous release how it should look, i.e. there should be an "i" icon with a "No Data Available" beneath the icon.  See sample mockup below:
 
<img width="139" alt="no data available" src="https://cloud.githubusercontent.com/assets/5589919/25101719/4a5512e6-2383-11e7-916a-475dca33d7f8.png">

**Comment by nthomas-redhat** [comment]
This issue is fixed. I could see the "No Data Available" icon mentioned in https://github.com/Tendrl/dashboard/issues/247#issuecomment-294568168 in the latest builds
