### ISSUE TITLE
Admin > Tasks: the tasks don’t show status

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#248]

**Comment by gnehapk** [comment]
@julienlim 
1) On task list view - Task status is shown in the third column.
2) On task detail view - Task status is shown against "status" field.
Can you please explain on which screen you are not able to see the status of task?

**Comment by nthomas-redhat** [comment]
@gnehapk One more issue I noticed is that the task events are not populated for all the tasks. For example I see this populated for `import cluster` but not for `create pool` or `create rbd`
etcd has data wrt the tasks mentioned above

**Comment by gnehapk** [comment]
@nthomas-redhat  Messages endpoint is getting failed(400/404 status). Hence, no event list is getting displayed for the particular task. Same as #233

**Comment by julienlim** [comment]
![screen shot 2017-04-10 at 10 28 45 am](https://cloud.githubusercontent.com/assets/5589919/24957996/c23d71d0-1f5b-11e7-9740-78580f1349b2.png)

**Comment by julienlim** [comment]
This is the UX design for the Tasks List: https://redhat.invisionapp.com/share/8N93NO7Q4#/screens/200318248

**Comment by gnehapk** [comment]
Fixed in the build "tendrl-dashboard: 1.2.1-04_09_2017_18_25_13".

**Comment by cloudbehl** [comment]
@Tendrl/qe Please verify it

**Comment by nthomas-redhat** [comment]
@gnehapk @cloudbehl The issue I mentioned at https://github.com/Tendrl/dashboard/issues/248#issuecomment-293182351 is still valid. Can you confirm whether its an API issue or not? If yes please raise an issue against API and provide enough details. We need to prioritize this issue

**Comment by gnehapk** [comment]
@nthomas-redhat Yes, its an API issue. Filed an issue under API repo - https://github.com/Tendrl/api/issues/158.
