### ISSUE TITLE
Active management (monitoring of CRUD operations) do not seem to be fully functional

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#249]
E.g. you can create pools, RBDs, resize RBDs, etc. but all you see are tasks created but the tasks never ever complete (even after 8+ hours).

**Comment by sankarshanmukhopadhyay** [comment]
We will have to wait and check if this issue is observed again. In the recent set of deployments of Tendrl this has not been observed by the developers. Will also wait on feedback from QE test runs.

**Comment by nthomas-redhat** [comment]
We haven't seen this issue in the latest builds and not reported by QE as well. Hence I am closing this issue, please re-open if found again
