### ISSUE TITLE
Create and Import cluster buttons do not work - unable to try and verify this

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#250]

**Comment by sankarshanmukhopadhyay** [comment]
We will wait for QE feedback on an import - unmanage - import cycle. The sandbox set up is a bit limited in terms of being able to do this repeatedly.

**Comment by mkudlej** [comment]
There is no button for creating cluster yet.

**Comment by nthomas-redhat** [comment]
Create cluster from Ui is not released yet for testing.
@julienlim , is there any other issues here? import or something doesn't work?
