### ISSUE TITLE
status inconsistent in top level list views vs. cluster object details > host list view

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#252]

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
@julienlim , Can you verify this and let us know please?

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk Looks like this has been fixed at quick glance.
