### ISSUE TITLE
charts look decent but would be better if text should be left justified per design

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#253]
Note: PatternFly has it center justified, but our design has it left justified

**Comment by sankarshanmukhopadhyay** [comment]
Can we include this fix in the upcoming code push?

**Comment by a2batic** [comment]
I would like to work on this issue

**Comment by a2batic** [comment]
@sankarshanmukhopadhyay @julienlim , on which screen are you facing this issue?

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available. @julienlim I checked in all the list views, please re-open if you see any issues
