### ISSUE TITLE
Create Pool workflow: default # of pools to create should always be set to 1

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#254]

**Comment by sankarshanmukhopadhyay** [comment]
Can we include this fix in the upcoming code push?

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
