### ISSUE TITLE
Create Pool workflow, it’s missing 1 button to let user create the pool after the Basic Settings is filled out (skipping Advance Configuration and Quotas)

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#255]
will update the UX design.

**Comment by julienlim** [comment]
@sankarshanmukhopadhyay @gnehapk @nnDarshan @nthomas-redhat 

[Create Pool design](https://redhat.invisionapp.com/share/2T9LPMEEB) updated to show the "Create Pool" button allowing skipping the Advanced Configuration and Quotas step.  Annotations covers the behavior for this button in the design.

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
