### ISSUE TITLE
RBD List view: RBD name should be left justified

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#256]

**Comment by sankarshanmukhopadhyay** [comment]
Can we include this fix in the upcoming code push?

**Comment by a2batic** [comment]
I would like to work on this issue

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
