### ISSUE TITLE
RBD List view: RBD name should be left justified, and there shouldn’t be so many spaces to say “     RBDName      in        MyCluster”

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#258]

**Comment by sankarshanmukhopadhyay** [comment]
Can we include this fix in the upcoming code push?

**Comment by a2batic** [comment]
I would like to work on this issue

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
@gnehapk Still I see many spaces to say “ RBDName in MyCluster”
Need fix this. Talk to @julienlim if you need any clarity around this

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk The rbd name is now left justified but there are still too many spaces in the <rbdname> in <clustername>
