### ISSUE TITLE
RBD List view: still missing utilization information

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#259]

**Comment by gnehapk** [comment]
@sankarshanmukhopadhyay Its because there is no response for monitoring data(Utilization) in API response. @anmolbabu @anivargi @nthomas-redhat Please check.

**Comment by nthomas-redhat** [comment]
I could see that the utilization graphs appearing in the RBD list view. Closing the issue

**Comment by julienlim** [comment]
@Tendrl/qe Has anyone verified if indeed this is populating with utilization data from the API response?  Hard to verify when it's showing 0%.  Would like for someone to load some data on the RBD to verify.
