### ISSUE TITLE
During RBD creation (wizard), if you create a new pool vs. use an existing pool, the left pane overwrites part of the wizard steps on top.

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#260]
Note: Left pane should be under the steps (per design) and not to the left of the steps.  Not in accordance with PatternFly.

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
@julienlim Can you please verify this agaist the latest build and let us know?

**Comment by julienlim** [comment]
Verified that the left hand panel is not overwriting the wizard steps
