### ISSUE TITLE
If only Ceph cluster, we shouldn’t see File Shares in the navigation

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#261]
as per https://tendrl.atlassian.net/secure/attachment/10100/Tendrl_%20UX%20Design%20Approach%20%26%20Information%20Architecture.pdf. The navigation behavior should look more like https://redhat.invisionapp.com/share/9XA4GEF4V#/screens

**Comment by julienlim** [comment]
@gnehapk @sankarshanmukhopadhyay @cloudbehl @nnDarshan @japplewhite 

Just to be clear, the goal is trying to provide context-sensitive navigational menus if only Ceph or Gluster is present.  If both types are present, then we would show all menu items.  This was documented in the [UX Design Approach and Information Architecture design document](https://tendrl.atlassian.net/secure/attachment/10100/Tendrl_%20UX%20Design%20Approach%20%26%20Information%20Architecture.pdf).

I've provided a snippet below for what it should look like when only Ceph / Gluster is present:
![screen shot 2017-06-12 at 9 51 35 am](https://user-images.githubusercontent.com/5589919/27037109-f20b84d2-4f54-11e7-8dc3-6161b2d13a15.png)

Note: Per https://github.com/Tendrl/dashboard/issues/424, the "File Shares" label should show "Volumes" instead.

**Comment by julienlim** [comment]
Note: It also needs to ensure that the appropriate Main Dashboard tabs are exposed, meaning don't expose a Ceph dashboard tab when Gluster is only present, and vice versa.

**Comment by julienlim** [comment]
@gnehapk @sankarshanmukhopadhyay @cloudbehl @nnDarshan @japplewhite @brainfunked @r0h4n @Tendrl/qe @nthomas-redhat 

Regarding this context-sensitive navigation issue, is it possible to put some kind of trigger after an import job that checks to see the different types of clusters that are present and updates the navigation bar accordingly.  Essentially, the 3 scenarios to consider are:

- Ceph only clusters
- Gluster-only clusters
- Both Ceph and Gluster clusters -- which is currently implemented

**Comment by mbukatov** [comment]
@ltrilety this is another example of gluster/ceph context differences we need to take into account, check for behavior described in https://github.com/Tendrl/dashboard/issues/261#issuecomment-308463505 should be part of import cluster web ui test case

**Comment by julienlim** [comment]
Requires some modularization in the UI to make this possible per @brainfunked.  Some refactoring needed.

**Comment by julienlim** [comment]
In reviewing the code, a suggested approach from @dgutride@redhat.com is to:
- Expose another menu item, i.e. an additional attribute for the menu item, which you can then set a condition for it to decide whether or not to show Pools, RBDs, or Volumes — see dashboard/src/modules/base/navigation/menu-svc.js
- Use a rootscope event (e.g. ImportCluster) to trigger when the menus get rebuilt
- Note: this similar trigger would also need to control which Ceph or Gluster (main) dashboard tab gets presented as well

@sankarshanmukhopadhyay @gnehapk @cloudbehl @brainfunked @r0h4n @Tendrl/qe @nthomas-redhat @nnDarshan @mcarrano
