### ISSUE TITLE
create pool, unable to click on any of the left pane steps (optional), typo

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#262]

**Comment by gnehapk** [comment]
@julienlim @sankarshanmukhopadhyay "Advanced Configuration" tab options depend on the some of the options selected in "Basic settings" tab. For example -

1) Minimum Replicas is only applicable for Standard/Replicated Pools. The Pool type is selected in "Basic settings" tab.
2) Minimum Replica value cannot be greater than Replica value. Again the Replica is being selected in "Basic settings" tab.

Hence we have disabled direct selection of left pane steps. User can proceed only by clicking "Next" button.

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Able to click on the left pane steps now. @julienlim please have look and let us know so that we can close the issue

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk I verified that the User is able to click the left pane now.
