### ISSUE TITLE
Admin > Tasks: The Tasks column should be left justified

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#263]

**Comment by a2batic** [comment]
I would like to work on this issue

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is available
