### ISSUE TITLE
Admin > Tasks: I submitted a bunch of create pool and create red tasks, and I can see them here, but they are all new tasks and don’t have status and no details at all.

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#264]
When do tasks go from “New” to “In Progress”?

**Comment by gnehapk** [comment]
@sankarshanmukhopadhyay We are continuously  polling for the status of each task in the task list. So if the response sends the status as "In Progress", the UI gets updated for it.

**Comment by nthomas-redhat** [comment]
This issue is not seen now. All the tasks transition to 'In Progress' and updates the status appropriately. Closing the issue
