### ISSUE TITLE
Create RBD Wizard - View Task Progress page/screen shows extra information

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#266]
When you create a RBD using a new pool, at the very end of the workflow when you see the View Task Progress page, you see all the wizard steps at the top, as well as the radio buttons for "What will you use for a backing pool? Choose existing pool Create new pool" and Create heading.  These extra text should not appear when the View Task Progress page is shown at the end of the workflow.
<img width="1280" alt="screen shot 2017-04-11 at 9 54 08 am" src="https://cloud.githubusercontent.com/assets/5589919/24912779/27cf9966-1e9d-11e7-8773-5f4ab586d2f4.png">

**Comment by julienlim** [comment]
@nthomas-redhat @sankarshanmukhopadhyay @cloudbehl @gnehapk

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk @nnDarshan @cloudbehl 

Also happens with Create Pool workflow too:

<img width="1280" alt="screen shot 2017-04-11 at 10 55 51 am" src="https://cloud.githubusercontent.com/assets/5589919/24915562/7cbaf60c-1ea5-11e7-9a21-223182be2aee.png">

**Comment by julienlim** [comment]
See https://redhat.invisionapp.com/share/EHAC6S0N4#/screens/217735642 for design.

**Comment by gnehapk** [comment]
@julienlim This task progress page is for "Create Pool" workflow. SInce the steps for create RBD is not completed, hence the UI is displaying the wizard steps. On the task progress page for create RBD, all the wizard steps are hidden.

**Comment by nthomas-redhat** [comment]
@gnehapk , How is user experience from UI? is it a single operation or two step process like user creates the pool first and continue with  rbd creation? it should not be like that. From a user's point of view it should be a single operation where both operation should be handled under the hood

**Comment by gnehapk** [comment]
@nthomas-redhat Yes. It should be single operation. So in the API, the UI should send the new pool creation reference along with the rbd creation details. But, single operation is not supported in the API.

**Comment by julienlim** [comment]
@nthomas-redhat @anmolsachan @gnehapk This is what we also had in the previous release.  I recognize that essentially you have to pass 2 calls, i.e. first call to create the pool then second call to create the RBD.  From a UI / user perspective, it should appear as a single operation/workflow.
