### ISSUE TITLE
Hovering to see tooltip for truncated label takes too long to see the tooltip

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#267]
In the Hosts listing, when I hover over the truncated cluster name (e.g. "MyCl..."), it took 2 seconds to see the tooltip show "MyCluster."  The slow UI response time gave me the impression that the functionality is not working.  The ask is to improve the UI response time so that it appears more responsive and not lagging as I had then moved on to other rows to take a look when the tooltip showed up when I had already moved away from the cell (in the row) when I initiated the hover.
<img width="1280" alt="screen shot 2017-04-12 at 8 59 53 am" src="https://cloud.githubusercontent.com/assets/5589919/24959082/9f4e38e0-1f5f-11e7-8aed-739f7c27275a.png">

**Comment by nthomas-redhat** [comment]
This is something we would like to take up during the beta cycle

**Comment by nthomas-redhat** [comment]
https://github.com/Tendrl/dashboard/issues/234
