### ISSUE TITLE
Server not found! message on login page

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#270]
Right after installation of tendrl I have `Server not found!` message written on login screen. After I reload the page the screen is loaded correctly.

Tested with:
tendrl-dashboard-1.2.1-04_13_2017_04_11_05.noarch
tendrl-performance-monitoring-1.2.2-04_13_2017_03_02_03.noarch
tendrl-node-agent-1.2.2-04_13_2017_03_06_16.noarch
tendrl-api-1.2.2-04_13_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_13_2017_04_42_04.noarch
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

![dashboard_ugly_login](https://cloud.githubusercontent.com/assets/22369801/24996010/6a4175a4-2031-11e7-99ea-303e8fe075a3.png)

**Comment by sankarshanmukhopadhyay** [comment]
Oh dear! This seems to have made a re-appearance. Anup/Nishanth - can we take a look at this, or, if provided with adequate information - I can run it under debug and provide additional detail.

**Comment by gnehapk** [comment]
@Tendrl/qe Fixed. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by fbalak** [comment]
@gnehapk It seems that the problem persists. This screenshot was taken right after tendrl installation. After reloading the page it seems ok.
Tested with:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
tendrl-dashboard-1.2.1-04_18_2017_04_11_04.noarch

![dashboard_ugly_login2](https://cloud.githubusercontent.com/assets/22369801/25118916/6db4bd5a-2418-11e7-8a21-77b8b6a98dce.png)

**Comment by ltrilety** [comment]
@fbalak seems to me more like browser issue, cached things

**Comment by fbalak** [comment]
It was really a problem with cached things. Now it seems good --> closing.
