### ISSUE TITLE
Wording on File Shares blank slate landing page needs to be updated

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#274]
The wording reads not very smoothly and also with both Ceph and Gluster, it needs to be clearer:

Current wording says:

No File Shares Detected. <-- note there should not be a period at the end

File Shares are detected when you create or import a cluster <-- missing period at the end

If you have already cluster created or imported and still do not see File Shares, make sure the File Shares are configured correctly.

![screen shot 2017-04-13 at 10 45 07 am](https://cloud.githubusercontent.com/assets/5589919/25009951/71a706ba-2036-11e7-9b81-36632c62a593.png)

I suggest the following:

No File Shares Detected

File Shares are detected when you create or import a Gluster cluster.

If a Gluster cluster has already been created or imported, and you still do not see File Shares, make sure the File Shares are configured correctly.

@rghatvis@redhat.com - please review and comment if the text I suggested is okay.  Thanks.

@gnehapk

**Comment by rghatvis** [comment]
Hey @julienlim , thanks for opening this issue. My thoughts:

- No File Shares Detected 
looks good

- File Shares are detected when you create or import a Gluster cluster. 
looks good

- If a Gluster cluster has already been created or imported, and you still do not see File Shares, make sure the File Shares are configured correctly.
looks good but I have an alternate version to suggest to match the voice and tone of the previous two messages which starts with "File Share" mention and to also keep it direct:
- "If no File Shares are detected after creating or importing a Gluster cluster, reconfigure the File Shares correctly."

So it would look like:
- No File Shares Detected
- File Shares are detected when you create or import a Gluster cluster.
- If no File Shares are detected after creating or importing a Gluster cluster, reconfigure the File Shares correctly.
What do you think?

**Comment by julienlim** [comment]
@gnehapk @dahorak @cloudbehl 

Please update text to what @rghatvis suggests:

No File Shares Detected
File Shares are detected when you create or import a Gluster cluster.
If no File Shares are detected after creating or importing a Gluster cluster, reconfigure the File Shares correctly.

Thank you.

**Comment by gnehapk** [comment]
@julienlim @rghatvis Will update the text. Thanks.

**Comment by gnehapk** [comment]
@Tendrl/qe @julienlim Updated the text. Please verify in tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by julienlim** [comment]
Wording now shows the following:
No File Shares Detected
File Shares are detected when you import a Gluster cluster.
If no File Shares are detected after creating or importing a Gluster cluster, reconfigure the File Shares correctly.

@gnehapk -- is the reason the 2nd line only says import cluster is because create cluster is not implemented in the UI yet, and this text will be updated to the wording suggested afterwards?

**Comment by gnehapk** [comment]
@julienlim Yes. Will update the text once Create cluster is supported in UI.

**Comment by julienlim** [comment]
Ack.
