### ISSUE TITLE
Pool create confirmation language 

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/dashboard#286]
When I create a single pool I get the message:

"An task has been submitted to the background for the Pool requested. You will be notified when processing is complete and the new Pools are ready for use."

It should read

"A task has been submitted for the Pool(s) requested. You will be notified when the task is complete and the new Pool(s) is ready for use."

**Comment by julienlim** [comment]
@rghatvis@redhat.com Please review if ok or if there should be other modifications.  Thanks.
