### ISSUE TITLE
RBD create panel defaults are incorrect

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/dashboard#291]
- When I create an RBD it chooses 128GB as the default size - it should be 1 GB

- It chooses 3 RBDs - it should default to 1

- The UI adds the numeric 1 2 3 to the names but in the case of a single RBD it should allow the admin to name it whatever he puts in the text box (not add a 1 to it)

**Comment by julienlim** [comment]
+1

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is already merged
