### ISSUE TITLE
User has to know to click refresh in order to see newly recreated pools or rbd's

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#293]
@brainfunked @gnehapk @cloudbehl @nnDarshan 
After creating pools or RBDs, and seeing the Task progress to completion (in Admin section), I expet to go to Pools or RBDs to see my newly created pools or RBDs but don't see them there.  I found that I have to refresh the browser in order to see the newly created pools or RBDs, and it's not obvious to the user that the user has to manually refresh the page in order to see them.  Is this intentional?

**Comment by shtripat** [comment]
So create pool flow in tendrl just executes the command to create the pool and does not explicitly add a record in etcd. The pool record would get created in etcd by next round of cluster sync (interval is 3 seconds).

Also UI does a pool from etcd every 10 seconds for listing the pools. So just by switching the view from job status to pools might not help as data might get refreshed after 10 seconds. Manual refresh does refresh so it works.

**Comment by nthomas-redhat** [comment]
@gnehapk , are tracking the job status and forcing a refresh once the job is complete?

**Comment by gnehapk** [comment]
@nthomas-redhat The UI is continuously polling the API response at a interval of 10 secs. So, if the job is updated in the backend, it will be reflected on the UI as well.
