### ISSUE TITLE
Create RBD is missing the unit/metric for the target size field, target size spinner too far away from the input field, trailing text does not need to be wordwrapped

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#294]
@gnehapk 

In Create RBD workflow, the Target Size field is missing the metric/unit, i.e. MB, GB, TB -- this should be displayed after the target size is entered.

Also, the target size spinner is a little too far away from where the value is specified.

The trailing text saying "39.9 GB Available" and "384 GB needed..." and warning message text should be on a single line and does not to be  wordwrapped.

<img width="1280" alt="screen shot 2017-04-19 at 3 34 29 pm" src="https://cloud.githubusercontent.com/assets/5589919/25199369/97154524-2518-11e7-97a3-4d555248f863.png">

See design at: https://redhat.invisionapp.com/share/EHAC6S0N4#/screens/217735641

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is already merged
