### ISSUE TITLE
List views columns are truncated and missing tooltips

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#296]
See host name and cluster name column.  When the name is truncated, there is no tooltip.  When the name is truncated to display "..." without a tooltip, user will have no idea what he/she is looking at.

See attached screenshots:
<img width="1280" alt="screen shot 2017-04-19 at 4 21 04 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200800/9b7eaeac-251d-11e7-8f41-ffc463fe7033.png">
<img width="1280" alt="screen shot 2017-04-19 at 4 21 31 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200801/9b874fbc-251d-11e7-8814-2013c1697c27.png">
<img width="1280" alt="screen shot 2017-04-19 at 4 20 56 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200815/aa2dd3ba-251d-11e7-9e27-08f8ab6344cf.png">

**Comment by gnehapk** [comment]
@julienlim  Its fixed and available at tendrl-dashboard-1.3.0-1.el7.centos.noarch.rpm. Please verify it.
