### ISSUE TITLE
Task Details issues

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#298]
@brainfunked @gnehapk @nnDarshan @cloudbehl @nthomas-redhat 

(1) Task Details only appears to work for Create Ceph Cluster, and not for other tasks e.g. Create Pool, Grow PG, etc.

(2) Since Task Details won't show any Steps per the [Task Details UX Design](https://redhat.invisionapp.com/share/8N93NO7Q4#/screens/200318247),  it does not make sense to show the word "Events" within the list of events that took place for the given task.

(3) Will the "events" listed in the Task Details show any other severity level other than "info"?  If not, perhaps it would be better not to show "Info" at all.

(4) The "events" seem to be missing timestamp information.

(5) "Time Submitted" text should not word wrap.

(6) Need a space in between Create and Cluster  -- see breadcrumbs "Tasks >> CreateCluster: ecf9a9a1-bf1e-49d7-b777-32ea2c11a696"

Attached is a screenshot of the Task Details for a Create Ceph Cluster:
<img width="1280" alt="screen shot 2017-04-21 at 3 01 00 pm" src="https://cloud.githubusercontent.com/assets/5589919/25292298/89525828-26a3-11e7-8828-3e9afc211366.png">

**Comment by mcarrano** [comment]
I created a modified mockup that reflects more closely the actual functionality, as implemented.  See attached.  When the task is complete, it would be nice if we can provide a link directly to the new object (in this case a link to cluster object details).  But at minimal, we should have a time stamp.  I simplified the info in the listing to remove severity if it won't be meaningful, and therefore left align the message field.  The "Events" label can also be removed.

![admin-task details-completed 1](https://cloud.githubusercontent.com/assets/6619860/25295368/357efc70-26b1-11e7-817b-1aa919f1b928.png)
