### ISSUE TITLE
install instructions documentation

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/dashboard#3]
There should be document which describes:

what software should be installed and how should be configured before installing Tendrl
Tendrl installation process
Tendrl post installation steps like configuration, service starting and so on

[was originally at https://tendrl.atlassian.net/browse/TEN-36]

**Comment by TimothyAsir** [comment]
Are you asking about rpm installation and configuration doc ?
If yes, what would be your suggestion on keeping the doc. Shall we keep it in trndrl-frontend-doc package or any other place ?

**Comment by mkudlej** [comment]
This is already done here https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference
