### ISSUE TITLE
Input forms have inconsistent styling

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#302]
@gnehapk 
Input forms seem to have inconsistent styling, i.e. the input fields sometimes have rounded edges, and sometimes straight edges.  Per PatternFly, they should all be straight edges.

The Next button in the Create Pool workflow should not be the blue cyan color but rather the other grey color like the "Cancel" button, which is enabled (per the design).

I've added screenshots from Create Pool and Create RBD workflows to highlight these styling inconsistencies:

<img width="992" alt="screen shot 2017-04-26 at 2 44 30 pm" src="https://cloud.githubusercontent.com/assets/5589919/25451107/0b083bf0-2a8f-11e7-9fe5-a2cd32becac9.png">

-- see Type and Cluster fields have rounded edges
-- note the color of the Next button.  See https://redhat.invisionapp.com/share/2T9LPMEEB#/screens/228811305.

<img width="1147" alt="screen shot 2017-04-26 at 2 45 02 pm" src="https://cloud.githubusercontent.com/assets/5589919/25451108/0b17fb9e-2a8f-11e7-8156-3bfb02649761.png">

-- see Cluster name (label probably should be "Cluster" to be consistent with the Create Pool workflow) and Target size spinner have rounded edges

**Comment by cloudbehl** [comment]
@julienlim @sankarshanmukhopadhyay This Issue reports 3 inconsistency in UI:
1) Related to the round edges.
2) Related to the color of "create pool" button.
3) Cluster Name should be Name in Create RBD.

Issue[1]: I am not able to reproduce it. I think you are using a MAC OS X and the user-agent stylesheet for Chrome with MAC OS gives a default border-radius of 5px to all the corners. Will mark this Issue as Enhancement and will try to solve it.

Issue[2]: Ack! I mark this issue as Bug.

Issue[3]: I can see Cluster Name written in UX of Create RBD(https://redhat.invisionapp.com/share/EHAC6S0N4#/screens/217735641). Please Acknowledge and will mark this Issue as Enhancement.
