### ISSUE TITLE
Dashboard for Gluster

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#303]

**Comment by cloudbehl** [comment]
According to the changes in the UX of Gluster Dashboard(https://redhat.invisionapp.com/share/589XIRJBW#/screens/213318368). I have few queries:
1) I can still see "FILES" status card in the new UX. This value is not coming from the API. Is it going to be there in UI? If yes then the required field is needed from the API and if not what should be there?
2) Clients information is not coming in the API.
3) Services status card:  So should I display it because as per the discussion with @brainfunked @nthomas-redhat we don't need to display it in UX as it doesn't provide much value to end user.
3) Most used bricks are not coming in the API.

@nthomas-redhat @brainfunked @sankarshanmukhopadhyay @anivargi @anmolbabu @gnehapk

**Comment by nthomas-redhat** [comment]
@cloudbehl , 
1. FILES is under discussion, leave it for now, we will update once finalized.
2. Clients information and Most used bricks WIP, will be available by 04/28
3. There was a discussion to show the alert panel instead of services, hope @gnehapk conveyed this to you?

**Comment by julienlim** [comment]
@cloudbehl @nthomas-redhat This is related to https://github.com/Tendrl/dashboard/issues/300.

**Comment by cloudbehl** [comment]
#310
