### ISSUE TITLE
Tendrl dashboard user name and password

### ISSUE THREAD

**Issue by andrewlove** [Tendrl/dashboard#318]
This might be a dumb question but what user name and password do I specify in the tendrl dashboard UI?

I cannot find a reference to the authentication mechanism used anywhere in the docs

**Comment by cloudbehl** [comment]
@andrewlove You need to follow this document[1] to setup Tendrl.

After setting up the tendrl you can follow this user guide[2] to create an admin user and that username and password to get logged into the dashboard.  

[1]. https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference
[2]. https://github.com/Tendrl/api/blob/master/docs/users.adoc

@andrewlove Fell free to ask if you have some more queries. :)

**Comment by andrewlove** [comment]
Perfect. Many thanks
