### ISSUE TITLE
Endoint Required for Configration tab inside Cluster Specific Data

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#323]
Below are the UX for the configuration tab of ceph[1] and gluster[2].

[1]. https://redhat.invisionapp.com/share/ZQAOY7FMP#/screens/221485892
[2]. https://redhat.invisionapp.com/share/ZQAOY7FMP#/screens/221494388

@anivargi @nthomas-redhat

**Comment by nthomas-redhat** [comment]
@anmolbabu @shtripat can you gather this information at the backend between you folks and point back to @anivargi so that API implementation can be done

**Comment by shtripat** [comment]
@anivargi in case of ceph the cluster configuration is available under maps/config and notification/utilization related configurations can be fetched from location in etcd saved by these modules.

Similarly, in case of gluster the configuration needs to be read directly from different locations in etcd.

@anmolbabu, please provide the etcd locations for notifications/utilization configurations.

As such there is no backend change required and API layer can read these details from etcd directly and present to UI.

**Comment by anmolbabu** [comment]
@shtripat Ack

@anivargi /notification_settings in etcd as per https://github.com/Tendrl/alerting/blob/develop/tendrl/alerting/objects/definition/alerting.yaml#L174 provides the entries in "Event Notifications" table but in backend the keys are grouped/cross-multiplied products of notification method and the type of notification(ex: email_osd_utilization_alert, email_cpu_alert) as per the discussions we had prior to its implementation. Also another most important point to note is that, the table shows availability related entries which do not exist as of now and requires implementation the gluster and ceph integrations(which I think @GowthamShanmugam is working on).

The utilization threshold info is available at /_NS/performance_monitoring/config/data/thresholds

Note: All this info is currently global and not available @ cluster level so when it is implemented @ cluster level, the paths are expected to slightly change...
