### ISSUE TITLE
Datapoints required for Gluster specific dashboard.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#324]
For the gluster specific dashboard[1]. 

- The iops endpoint is this instance is giving empty array(http://10.70.42.170/api/1.0/monitoring/cluster/gc3b125e-4769-4071-a349-e82b380c11f4/iops).

- I am not able to find te endpoint for displaying the throughput data in gluster cluster-specific page.

[1]. https://redhat.invisionapp.com/share/589XIRJBW#/screens/213318639

**Comment by anmolbabu** [comment]
1. IOPs will not be available for gluster cluster as this requires the costly operation of having to start and stop gluster volume profile which comes with a note "Running profile command can affect system performance while the profile information is being collected. Red Hat recommends that profiling should only be used for debugging." and hence the decision to use it for purpose of monitoring was stayed -- "let us park this as well" to quote the decision
@nthomas-redhat Can you please confirm the same

2. @anivargi Can you provide the endpoint corresponding to gluster cluster network throughput that wraps: http://xx.xx.xx.xxx:5000/monitoring/clusters/gc3b125e-4769-4071-a349-e82b380c11f4/throughput/cluster_network/stats for use by UI

**Comment by nthomas-redhat** [comment]
> IOPs will not be available for gluster cluster as this requires the costly operation of having to start and stop gluster volume profile which comes with a note "Running profile command can affect system performance while the profile information is being collected. Red Hat recommends that profiling should only be used for debugging." and hence the decision to use it for purpose of monitoring was stayed -- "let us park this as well" to quote the decision
> @nthomas-redhat Can you please confirm the same
> But yes, probably we need checks in place to error out when used for a gluster cluster instead of just returning a blank array which I can add.

yes that is what we discussed.

@japplewhite, @brainfunked , hope you are in agreement with this

**Comment by japplewhite** [comment]
@nthomas-redhat I am in agreement with this at the gluster level, however I would like to address disk IOPs at the node level and possibly later be able to aggregate this in the UI. We should take the new spec for disks and update information from iostat (or proc):

[root@tendrl ~]# iostat -d
Linux 3.10.0-514.16.1.el7.x86_64 (tendrl) 	05/11/2017 	_x86_64_	(1 CPU)

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda            3579.52     63748.14     33084.89  326837346  169626553
dm-0            714.23     39301.51       976.89  201499227    5008513
dm-1          14137.37     24440.95     32108.65  125309008  164621376
dm-2              0.01         0.06         0.00        312          0

where tps is the number of IOPs. We can aggregate this for gluster to get IOPS for a volume or cluster.
