### ISSUE TITLE
Cluster List doesn't have alert count!

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#326]
I will still consider cluster list as incomplete from the UI perspective. As we are still showing Alert count as "NA".

@anivargi @r0h4n @nthomas-redhat @shtripat  Can anyone put some light on this topic.

**Comment by anivargi** [comment]
@anmolbabu Can you add the alerts count to each cluster as well, so it can be displayed on the UI?

**Comment by cloudbehl** [comment]
@anmolbabu Is it Done?

**Comment by anmolbabu** [comment]
@cloudbehl yes
