### ISSUE TITLE
Host list on Ceph Import Cluster page is empty

### ISSUE THREAD

**Issue by dahorak** [Tendrl/dashboard#335]
With recent version of Tendrl packages, the Host list on _Import Cluster_ page for importing _Ceph_ cluster is empty:
![import_cluster_ceph](https://cloud.githubusercontent.com/assets/4759779/26064020/045021f0-3990-11e7-91da-7ff5499c9dbb.png)

While when I chose _Gluster_ cluster, the appropriate nodes are visible:
![import_cluster_gluster](https://cloud.githubusercontent.com/assets/4759779/26064026/0a531d32-3990-11e7-970b-6e2248afbf58.png)

And `GetNodeList` _api_ call seems to contain all required information:
[GetNodeList.txt](https://github.com/Tendrl/dashboard/files/1001472/GetNodeList.txt) (NOTE: the json is reformated)
![getnodelist](https://cloud.githubusercontent.com/assets/4759779/26064069/25dc785a-3990-11e7-9d29-3b1e5dc67e85.png)

List of related packages:
```
tendrl-api-1.2.3-05_15_2017_01_51_04.noarch
tendrl-api-doc-1.2.3-05_15_2017_01_51_04.noarch
tendrl-api-httpd-1.2.3-05_15_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_15_2017_17_59_12.noarch
tendrl-dashboard-1.2.3-05_15_2017_04_11_04.noarch
tendrl-node-agent-1.2.3-05_15_2017_18_23_15.noarch
tendrl-node-monitoring-1.2.3-05_15_2017_18_17_56.noarch
tendrl-performance-monitoring-1.2.3-05_15_2017_18_17_13.noarch
```

**Comment by cloudbehl** [comment]
@dahorak ack!

@nthomas-redhat  @anivargi Is there any change in the backend or the API for the Ceph host listing?

**Comment by dahorak** [comment]
It seems that this issue might have connection with the fact, that I have two separated networks for ceph ([Public Network and Cluster Network](http://docs.ceph.com/docs/master/rados/configuration/network-config-ref/)).
I'll confirm it once I'll have new cluster installed.

**Comment by ltrilety** [comment]
I have the same issue, however after restart of `tendrl-node-agent` on all machines it works correctly.

**Comment by GowthamShanmugam** [comment]
I Have tested this i don't see any issue like this, it listed all ceph nodes correctly .
![page](https://cloud.githubusercontent.com/assets/15073590/26445894/7e333134-415f-11e7-8e23-8fdf108af0e0.png)

**Comment by dahorak** [comment]
@GowthamShanmugam I'll try to reproduce it and prospectively give you access to my cluster.

**Comment by GowthamShanmugam** [comment]
@mbukatov @nthomas-redhat @shtripat @r0h4n 
This problem is coming in downstream alpha build 
tendrl-commons-3.0-alpha.3.el7scon.noarch
tendrl-node-monitoring-3.0-alpha.el7scon.noarch
tendrl-node-agent-3.0-alpha.3.el7scon.noarch

now in new this problems is solved in upstream build so next beta version should not have this problem
