### ISSUE TITLE
advance configuration typo

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#342]
There's typo in menu during creating a pool. There should be 'Advanced Configuration' not 'Advance Configuration'.

![image](https://cloud.githubusercontent.com/assets/22369834/26195301/97908450-3bbb-11e7-9e9a-1929340a49b0.png)

Used package:
tendrl-dashboard-1.2.3-05_18_2017_04_11_06.noarch

**Comment by gnehapk** [comment]
@ltrilety Its fixed and available at tendrl-dashboard-1.3.0-1.el7.centos.noarch.rpm. Please verify it.

**Comment by ltrilety** [comment]
Fixed
Checked on:
tendrl-dashboard-3.0-alpha.3.el7scon.noarch
