### ISSUE TITLE
Back/Cancel button

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#354]
When there is no cluster to import and user chooses to import some on home page, the UI correctly says there's no cluster to import however there's no possibility to go back. At least no way how to do that without using browser back button as there's no 'Back' or 'Cancel' button available.

![image](https://cloud.githubusercontent.com/assets/22369834/26294568/0a94eb92-3ec5-11e7-918e-5c4203cdee8d.png)

Used package:
tendrl-dashboard-1.3.0-05_22_2017_04_11_04.noarch

**Comment by gnehapk** [comment]
@ltrilety The fix is available in the latest build. Please verify it.
