### ISSUE TITLE
nodes used for cluster creation available for other clusters

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#367]
Nodes which were used during a cluster creation are still listed as available nodes for another cluster creation.

Used packages:
tendrl-dashboard-3.0-alpha.1.el7scon.noarch
tendrl-api-3.0-alpha.el7scon.noarch
tendrl-api-doc-3.0-alpha.el7scon.noarch
tendrl-commons-3.0-alpha.2.el7scon.noarch
tendrl-performance-monitoring-3.0-alpha.el7scon.noarch
tendrl-api-httpd-3.0-alpha.el7scon.noarch
tendrl-node-agent-3.0-alpha.2.el7scon.noarch

**Comment by sankarshanmukhopadhyay** [comment]
The fix for this is in the codebase and the latest packages (being brewed for the project) will contain them. Additionally, given the package NVR cited, perhaps a bug on Red Hat Bugzilla would be appropriate.
