### ISSUE TITLE
cluster creation pages are not correctly scaled

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/dashboard#368]
When the resolution during cluster creation is less then 1440x{Something} some fields are badly placed and displayed on several pages.

On this particular page individual hosts cannot be chosen because checkbox field is covered by name field. Moreover many fields seems to be on bad place and some fields are overlapping others.
![image](https://cloud.githubusercontent.com/assets/22369834/26398746/bf61e67c-407a-11e7-9839-9c25bd165936.png)

Similar here, roles for host are not visible.
![image](https://cloud.githubusercontent.com/assets/22369834/26399080/e5dcc0b4-407b-11e7-8315-1a1dbcb8c03c.png)
 
...

Note: my resolution was 1280x800

Used packages:
tendrl-dashboard-3.0-alpha.1.el7scon.noarch
tendrl-api-3.0-alpha.el7scon.noarch
tendrl-api-doc-3.0-alpha.el7scon.noarch
tendrl-commons-3.0-alpha.2.el7scon.noarch
tendrl-performance-monitoring-3.0-alpha.el7scon.noarch
tendrl-api-httpd-3.0-alpha.el7scon.noarch
tendrl-node-agent-3.0-alpha.2.el7scon.noarch

**Comment by cloudbehl** [comment]
Please verify this bug.
tendrl-dashboard-3.0-alpha.5.el7scon.noarch.rpm

**Comment by ltrilety** [comment]
seems fine
