### ISSUE TITLE
Create File Share: Type should have 2 volume types

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#390]
Type should have 2 volume types: 3-way distributed replicated and Erasure Coded.  

2-way distributed replicated is left off as we will plan on  arbiter volumes to cover that scenario in the future.

@japplewhite can confirm.

@gnehapk @nnDarshan @cloudbehl

**Comment by japplewhite** [comment]
@julienlim yes that's correct. In the very near future we will need to add 2 way with arbiter but not now.
