### ISSUE TITLE
Partition per device(Default value need to change) for SSD and HDD.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#410]

**Comment by gnehapk** [comment]
@cloudbehl What is the default value for partition per device.

**Comment by cloudbehl** [comment]
@gnehapk So the value is getting calculated for the max but that value is just for the HDD. For the SSD the value should be 4.

@shtripat Can you tell us what will the value of partitions per device. In case of SSD and HDD.

**Comment by gnehapk** [comment]
This functionality is not supported in backend yet. Will reopen the issue once its supported by the backend.
