### ISSUE TITLE
Ability to drilldown from charts in dashboards

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#423]
Users would like the ability to click on any item in the dashboard (charts) and drill down to see the specific details.

E.g. in the heatmap in the Ceph cluster object details dashboard (overview tab), user wants to be able to click on any cell to see what object is affected and the value that cause the color to be red, and from there be able to be able to get to the actual object.  If it's a host, it would go to the related host to see its details.

@japplewhite @r0h4n @nthomas-redhat @gnehapk @nnDarshan @cloudbehl @mcarrano

**Comment by r0h4n** [comment]
Closing this one since it will e handled via the Tendrl grafana dashboard (maybe)
