### ISSUE TITLE
Issue with Create cluster task status

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/dashboard#425]
Currently the status of the create cluster job(ceph and gluster) is set to `finished` as soon as the create cluster is done. As part of the create cluster operation tendrl does a import as well as post operation to the create cluster and a bunch of jobs are created for the same. dashboard need to keep track them as well and update the task accordingly before the create cluster job is marked as completed

**Comment by nthomas-redhat** [comment]
@r0h4n ^

**Comment by r0h4n** [comment]
@cloudbehl the requirement here is a generic one, the UI should inspect all child job statuses (they should be "finished" or "failed") and then based on the child jobs status show the parent job status ("finished" if all child jobs "finished", "failed" if any child job "fails")

**Comment by mbukatov** [comment]
@r0h4n Reading the description of the issue, I would classify this as a problem of the backend, not ui/dashboard. When the api indicates that a job is finished, I would not expect that there are still some subtasks of this job running. In other words, backed should flag a job as finished only when all (if any) subtasks are finished first. Or am I missing anything?

**Comment by mbukatov** [comment]
@r0h4n It this related to https://github.com/Tendrl/api/issues/221?
