### ISSUE TITLE
"make snapshot" target for building packages from develop branch

### ISSUE THREAD

**Issue by dahorak** [Tendrl/dashboard#442]
`make snapshot` target is not implemented and because of that the build trigger jobs are failing:
https://ci.centos.org/view/tendrl-build/job/tendrl-build-1-develop-dashboard/

It would be good if it will be possible to build _snapshot_ version package (usable mainly for packages from develop and prospectively from feature branches).

**Comment by r0h4n** [comment]
Please note updated branching model: https://www.redhat.com/archives/tendrl-devel/2017-July/msg00004.html

Let me know if you have questions, closing this one now

@TimothyAsir @dahorak
