### ISSUE TITLE
UI requests notifications after logout

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#463]
After user signs out from Tendrl UI and after user is redirected to login page the site still requests GET `hostname/api/1.0/notifications` every few seconds. All these requests fail as Unauthorized. Issue disappears after site is reloaded.

Tested with:
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch

**Comment by mbukatov** [comment]
ok
