### ISSUE TITLE
Without ceph provisioner, we should not allow create cluster wizard for ceph to be started

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#464]
When there is no ceph-installer service installed and running on Tendrl Server, we should report this fact when one tries to create ceph cluster, instead of allowing the user to start create ceph cluster wizard.

## Steps to reproduce

1. Install Tendrl Server without ceph-installer
2. Try to create ceph cluster

## Additional Information

I consider having Tendrl Server without ceph-installer is a supported scenario based on current [Installation Reference](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference):

> Install ceph installer if you want to manage/create ceph clusters

 and discussion on tendrl-devel list:

* https://www.redhat.com/archives/tendrl-devel/2017-May/msg00046.html

**Comment by cloudbehl** [comment]
@brainfunked @nthomas-redhat @r0h4n I think it has more to do with back-end and the API, They should pass this information to the dashboard and then dashboard can handle these conditions.

**Comment by r0h4n** [comment]
@mbukatov Lets revisit this once we start supporting CreateCluster
