### ISSUE TITLE
There is no host filter in Create Cluster - Network & Hosts page of create ceph cluster wizard

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#465]
When one tries to create ceph cluster via Tendrl and reaches 2nd page "Network & Hosts" where machines can be selected, the wizard doesn't provide any way to filter machines. Note that the filtering is available on the next page, when roles are assigned to the selected machines.

![todo-issue 001](https://user-images.githubusercontent.com/4759819/27496413-1a75d454-5856-11e7-8c57-4ec0dd18c797.png)

Version
======

tendrl-dashboard-1.4.2-1.el7.centos.noarch

**Comment by r0h4n** [comment]
Create Cluster is being parked for now. closing this one
