### ISSUE TITLE
There is no ceph status/health information in ceph dashboard

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#466]
On the ceph dashboard page, ceph health status information is not clear.

By ceph health status I mean the same kind of information as provided by:

```
# ceph -c /etc/ceph/ceph_20175231498243714307.conf -s
    cluster 0f34eef9-34fd-4cdb-ad6f-79aa33cef9bf
     health HEALTH_WARN
            too few PGs per OSD (6 < min 30)
     monmap e2: 1 mons at {mbukatov-usm1-mon1=10.34.108.121:6789/0}
            election epoch 4, quorum 0 mbukatov-usm1-mon1
        mgr no daemons active 
     osdmap e150: 30 osds: 30 up, 30 in
            flags sortbitwise,require_jewel_osds,require_kraken_osds
      pgmap v478: 64 pgs, 1 pools, 0 bytes data, 0 objects
            1056 MB used, 25948 GB / 25949 GB avail
                  64 active+clean
```

Version
======

Listing related packages on Tendrl Server machine:

```
# rpm -qa 'tendrl-*'
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
tendrl-api-doc-1.4.2-1.el7.centos.noarch
# rpm -qa | grep ceph
ceph-ansible-2.2.10-29.ge20001e.el7.noarch
ceph-installer-1.3.0-10.g0e9fec2.el7.noarch
```

Reproducer
==========

1. Install Tendrl Server using tendrl-ansible
2. Create or import ceph cluster into Tendrl
3. Go to ceph dashboard page
4. Try to learn ceph health status based on information provided there and compare that with information provided by `ceph -s` command

Actual results
===========

There is no ceph health status on the ceph dashboard page, see:

![todo-issue 002](https://user-images.githubusercontent.com/4759819/27497422-d22dc88c-585a-11e7-85b0-3957ed8873da.png)

While the icon next to the name of the cluster is indicating some problem, no further details are provided, which is not sufficient for the admin to immediately understand the state of the cluster - especially when all values provided by the dashboard are classified as green.

Expected results
=============

Full health status should be provided on the dashboard, so that it's comparable with information provided by `ceph -s`.

In this particular case it would mean to convey this information:

```
     health HEALTH_WARN
            too few PGs per OSD (6 < min 30)
```

**Comment by gnehapk** [comment]
@julienlim @mcarrano As per the @mbukatov comment, please make the necessary changes in UI design to show the ceph health status more clearly.

**Comment by r0h4n** [comment]
Re-open when we have designs updated for the issue
