### ISSUE TITLE
There is no time in "Time Submitted" value on task detail page

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#469]
When new task is submitted, the task details page doesn't include full time of the submission, even though one field on the page reads "Time Submitted", only a date of submission is provided.

The root cause of this issue may be in the backend, if that is the case, move this issue to the appropriate component.

## Version

```
# rpm -qa 'tendrl-*'
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
```

## Reproducer

1. Install Tendrl using tendrl-ansible
2. Submit new task via web ui, eg. CreateCluster
3. Go to the task details page of the new task
4. See time submitted information

## Actual Result

The task detail page shows just a date, but no time, as a value for *Time Submitted* field. In my case, it contains:

> Time Submitted: 26 Jun 2017

As can be seen here:

![todo-issue 008](https://user-images.githubusercontent.com/4759819/27545517-45c27ac2-5a90-11e7-8da4-046c91707909.png)

## Expected Result

Full timeout is provided, such as:

> Time Submitted: 26 Jun 2017 14:43:10

This is just an example to illustrate the point, we need to check which time stamp format we should follow in this case.

**Comment by sankarshanmukhopadhyay** [comment]
Fair point! This has been raised as a production support topic too.

**Comment by mbukatov** [comment]
Ok.
