### ISSUE TITLE
Value range of Network Trend chart is misleading for a new cluster

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#475]
Description of chart in *Network Trend* widget in cluster dashboard is misleading for a new cluster (which is younger than 24 hours) as description of the x axis states *Last 24 hours* while the data there can't possibly be there from such time range (the new cluster didn't exist 24 hours ago).

## Version

```
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
```

## Reproducer

1. Install Tendrl using tendrl-ansible (on fresh machines for server and storage nodes)
2. Create gluster cluster via web ui and wait for the task to complete
3. Go to cluster dashboard of the new cluster
4. Find *Network Trend* widget there

## Actual Results

Chart in *Network Trend* widget in cluster dashboard is misleading:

* description of the x axis states *Last 24 hours*
* the values there are provided for last few minutes

See:

![todo-issue 011](https://user-images.githubusercontent.com/4759819/27602181-2e989402-5b72-11e7-82eb-509e619813f7.png)

That said, there is a visual hint that the values presented doesn't cover the full 24 hour range: the density of data points is low - but someone who sees that for the first time would not notice that as he or she would lack the experience of fully loaded chart.

## Expected Results

When the values for last 24 hours are not available, we need to make sure to convey this information somehow:

* updating the description to match the values presented (eg. the description would read "last 2 hours" instead when there are values only from last 2 hours)
* changing the description in a static way to make this clear (I have no good example here)
* something else

Those examples are there just to demonstrate the point, we need to review design guidelines while having implementation aspects in mind.

**Comment by r0h4n** [comment]
Closing this issue, we will be focusing on fixing these issues in Tendrl Grafana dashboard

**Comment by mbukatov** [comment]
ok
