### ISSUE TITLE
Errors in package

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/dashboard#57]
I've found this errors in last package from https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/build/481995/ 
All errors should be fixed and it will be great to fix also one warning.
```$ rpmlint tendrl-frontend-1.1-1.el7.centos.noarch.rpm 
tendrl-frontend.noarch: W: incoherent-version-in-changelog 0.0.1-1 ['1.1-1.el7.centos', '1.1-1.centos']
tendrl-frontend.noarch: E: script-without-shebang /var/www/tendrl/commons/scss/main.css
tendrl-frontend.noarch: E: script-without-shebang /var/www/tendrl/index.html
tendrl-frontend.noarch: E: unknown-key RSA#e879b811 (MD5
1 packages and 0 specfiles checked; 3 errors, 1 warnings.
```

**Comment by cloudbehl** [comment]
@mkudlej can you tell steps to reproduce this error?

**Comment by TimothyAsir** [comment]
@gnehapk , rpmlint <package> will show this error
$ rpmlint tendrl-frontend-1.1-1.el7.noarch.rpm
tendrl-frontend.noarch: W: incoherent-version-in-changelog 0.0.1-1 ['1.1-1.el7', '1.1-1']
tendrl-frontend.noarch: E: script-without-shebang /var/www/tendrl/index.html
tendrl-frontend.noarch: E: script-without-shebang /var/www/tendrl/commons/scss/main.css
1 packages and 0 specfiles checked; 2 errors, 1 warnings.

**Comment by gnehapk** [comment]
@TimothyAsir Is the error still coming?

**Comment by mbukatov** [comment]
@gnehapk yes, here you can check the last result from the CI:

https://ci.centos.org/view/Tendrl/job/tendrl-0-1-package-validation-rpmlint/lastCompletedBuild/testReport/usmqe_tests.rpm/test_rpm/test_rpmlint_tendrl_dashboard_/
