### ISSUE TITLE
Repository name changes

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/dashboard#62]
Repository names need to be updated to follow lowercase, hyphenated convention. In this case need to drop the tendrl prefix and change the name to dashboard

**Comment by nthomas-redhat** [comment]
https://github.com/Tendrl/specifications/pull/24

**Comment by r0h4n** [comment]
@Tendrl/tendrl_frontend Please finish this task on highest priority  (cc @kamleshverma1 )

**Comment by gnehapk** [comment]
Done.
