### ISSUE TITLE
cluster import flow should match with UX design

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/dashboard#63]
We are going with dynamic generation and we have common form generator.
we are using this form generator for generate the form but in the import cluster case , we have different ux design , not common select box or textbox as we have in form generator.
so finally for import cluster we are not going ahead with dynamic generation for now. it will be static but we will use directive for table view.

**Comment by nthomas-redhat** [comment]
Looks irelavant at the moment. Closing the issue
