### ISSUE TITLE
Not documented dependency

### ISSUE THREAD

**Issue by fbalak** [Tendrl/dashboard#78]
When running `gulp` command there is an error during `PhantomJS` installation: "error while loading shared libraries: `libfontconfig.so.1`: cannot open shared object file: No such file or directory." This can be resolved on Centos by:
`sudo yum install fontconfig`
This step should be documented.

**Comment by TimothyAsir** [comment]
@fbalak , its now added as a dependency in https://github.com/Tendrl/dashboard/pull/201. This issue can be closed once the pr is merged.

**Comment by fbalak** [comment]
@TimothyAsir ok

**Comment by nthomas-redhat** [comment]
Closing the issue as the PR is merged
