### ISSUE TITLE
Landing Page Text Change

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#93]
For the landing page, @rghatvis@redhat.com suggests that we re-word the text, i.e. remove “please” and instead saying: “Create or import a cluster to get started.”

@mcarrano This was listed in https://redhat.invisionapp.com/share/6T900V2ZX#/screens/198042644/comments/76877561 -- noting this as an issue so it can be changed.

**Comment by kamleshverma1** [comment]
resolved at #97
